### ISSUE TITLE
it got memory leaky problem

### ISSUE THREAD

**Issue by show-me-code** [elijahr/aiozyre#3]
it got a memory leaky problem, when sending message ,the memory occupied will increase and not dorp
I'll be appreciate it if you can fix it
[
<img width="950" alt="WechatIMG1826" src="https://user-images.githubusercontent.com/27920806/87402083-9ff86a80-c5ed-11ea-86c2-10c2e952c1cc.png">
](url)

**Comment by elijahr** [comment]
@show-me-code thanks for filing an issue. Can you provide your code so that I might reproduce the issue?

**Comment by show-me-code** [comment]
Thanks for your reply.
 I just used your example chatter.py and send many words in the chat room. 
Use the memory monitor you can find the memory Leakey(by the way, I used memory_profiler as memory monitor)

**Comment by elijahr** [comment]
@show-me-code thank you. I'll look into it sometime in the next week when I have time. I suspect it is something in https://github.com/elijahr/aiozyre/blob/master/src/aiozyre/util.pyx

**Comment by show-me-code** [comment]
I am looking forward to your update and I'll trying to fin the problem either😊

**Comment by elijahr** [comment]
@show-me-code I wasn't able to get memory_profiler working, but I think I have found the memory leaks. Can you see if the branch in https://github.com/elijahr/aiozyre/pull/4 fixes the issue for you?

**Comment by elijahr** [comment]
@show-me-code I fixed a few memory leaks, but I don't know if it is all of them. Please try v1.1.5 (I will be releasing this on PyPI shortly) and let me know how it goes.
